#General Config. This config is synced from server to client.
[general]

	#Pump Settings
	[general.pump]
		#mB of Heavy Water that is extracted per block of Water by the Electric Pump with a Filter Upgrade.
		# Default: 1000
		# Range: 100 ~ 1000
		pumpHeavyWaterAmount = 1000
