# Default: 1.0
# Range: 0.0 ~ 16.0
uiScale = 1.0
# Default: -1
# Range: -1 ~ 1
uiXAnchor = -1
# Default: 8
# Range: -1000 ~ 1000
uiXOffset = 8
# Default: 0
# Range: -1 ~ 1
uiYAnchor = 0
# Default: 0
# Range: -1000 ~ 1000
uiYOffset = 0
