#.
#CEC blocks comportements
[kinetics]

		#.
		#.
		#kinetic stats
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				tofu_encased_shaft = 0.0
				tofu_encased_cogwheel = 0.01
				tofu_metal_shaft = 0.0
				tofu_cogwheel = 0.01
				yuba = 0.0
				tofu_large_cogwheel = 0.01
				tofu_encased_large_cogwheel = 0.01
				tofu_gearbox = 0.01

			#.
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v2.capacity]
				tofu_water_wheel = 32.0
