#Client configuration settings
[client]

	#Configure rendering
	[client.render]
		#Render player faces on advanced hunter or vampires
		advancedMobPlayerFaces = true
		#Render vampire eye/fang face overlay
		vampireEyes = true
		#Render fog in vampire biome. Might be enforced server side
		vampireForestFog = true
		#Render full screen colored overlays for effects like vampire levelup
		renderScreenOverlay = true

	#Configure GUI
	[client.gui]
		#X-Offset of the level indicator from the center in pixels
		# Default: 0
		# Range: -250 ~ 250
		levelOffsetX = 0
		#Y-Offset of the level indicator from the bottom in pixels
		# Default: 47
		# Range: 0 ~ 270
		levelOffsetY = 47
		#Render skill menu button in inventory
		skillButtonEnable = true
		#Force the guiSkillButton to the following x position from the center of the inventory, default value is 125
		# Default: 125
		# Range: > -2147483648
		overrideGuiSkillButtonX = 125
		#Force the guiSkillButton to the following y position from the center of the inventory, default value is -22
		# Default: -22
		# Range: > -2147483648
		overrideGuiSkillButtonY = -22
		#Disable the FOV change caused by the speed buf for vampire players
		disableFovChange = false
		#Disable the effect of blood vision. It can still be unlocked and activated but does not have any effect
		disableBloodVisionRendering = false
		#Disable the rendering of the action cooldowns in the HUD
		disableHudActionCooldownRendering = false
		#Disable the rendering of the action durations in the HUD
		disableHudActionDurationRendering = false

	#Overlay rendering
	[client.overlay]
		#Disable the rendering of the bat overlay in the HUD
		enableHudBatOverlayRendering = true
		#Disable the rendering of the village raid overlay in the HUD
		enableVillageRaidOverlayRendering = true
		#Disable the rendering of the disguise overlay in the HUD
		enableDisguiseOverlayRendering = true
		#Disable the rendering of the faction level overlay in the HUD
		enableFactionLevelOverlayRendering = true
		#Disable the rendering of the nearby vampire overlay in the HUD
		enableNearbyVampireOverlayRendering = true
		#Disable the rendering of the rage overlay in the HUD
		enableRageOverlayRendering = true
		#Disable the rendering of the sun overlay in the HUD
		enableSunOverlayRendering = true

	[client.internal]
		#Action ordering
		actionOrder = ""
		#Minion task ordering
		minionTaskOrder = ""
